services:
  ai-shorts:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ai-youtube-shorts

    working_dir: /app

    volumes:
      - .:/app
      - ./output:/app/output
      - ./downloads:/app/downloads
      - ./cache:/app/cache

    env_file:
      - .env

    stdin_open: true
    tty: true
